### ISSUE TITLE
Please add support for PF2

### ISSUE THREAD

**Issue by apoapostolov** [mikkerlo/fvtt-token-self-initiative#1]
This is very useful when player needs to set his initiative to a result to a skill check (such as Stealth) in PF2, so please expand support to include PF2 as well.

**Comment by mikkerlo** [comment]
Hi! Sorry for the delayed answer, could you explain in a little more detail what you want here? The ability to use a different stat for the roll?

**Comment by apoapostolov** [comment]
Hello, sorry it took me this long to find out your question. I rarely use all of GitHub functions.

PF2 rules allow to make custom initiative rolls using any Skill, usually Stealth when stealthily approaching an enemy. This means a roll you made several minutes ago will assign your initiative. By making this mod work n PF2 you would allow players who remember their Stealth check value to enter it as initiative.

**Comment by mikkerlo** [comment]
Sorry for the long answer. But this mod works in pf2 as is, we actually using it in our sessions. Will close the issue for now, but if something is not resolved on your side fell free to reopen it.

**Comment by apoapostolov** [comment]
Please close it. The issue back then was that the mod did not appear in PF2 and was system-locked for 5E. Sorry I never responded, it's all good now, I am using it.
