### ISSUE TITLE
Multiple assign

### ISSUE THREAD

**Issue by Nupky** [mikkerlo/fvtt-token-self-initiative#6]
Hey, finally! Someone lets me skip the rolling required by Foundry. I want to use normal dice and just enter in the details. Would love it if I could assign multiple tokens, or use the group assign module to assign all enemies of the same type?

**Comment by mikkerlo** [comment]
Usually for me it means that I have choose someone wrong, I can add option to make it your way in the settings, sounds good?

P.S. My players also roll dices and puts initiative through this script, since they can have control over multiple tokens, this can be bad.

**Comment by mikkerlo** [comment]
Close due inactivity
